const path=require('path');
const express = require('express');
const adminController = require('../controller/adminController');
const islogin =require('../mw/isAuth');
const router = express.Router();
router.get('/',islogin, adminController.adminHome);
router.post('/add_skill',islogin,adminController.postSkill);
router.post('/add_degree',islogin,adminController.postDegree);
router.post('/add_project',islogin,adminController.postProject);
router.post('/add_blog',islogin,adminController.postBlog);
router.post('/delete_degree',islogin,adminController.postDegreeDelete);
router.post('/delete_skill',islogin,adminController.postSkillDelete);
router.post('/delete_project',islogin,adminController.postProjectDelete);
router.post('/delete_blog',islogin,adminController.postBlogDelete);
router.post('/readed_message',islogin,adminController.postReadedMessage);
router.post('/delete_message',islogin,adminController.postDleteMessage);
router.post('/skill_note_update',islogin,adminController.skillNoteUpdate);
router.post('/objective_update',islogin,adminController.objectiveUpdate);
router.post('/edit_degree',islogin,adminController.editDegree);
router.post('/edit_project',islogin,adminController.editProject);
router.post('/edit_blog',islogin,adminController.editBlog);
router.post('/update-degree',islogin,adminController.updateDegree);
router.post('/update-project',islogin,adminController.updateProject);
router.post('/update-blog',islogin,adminController.updateBlog);
router.post('/update_profile_pic',islogin,adminController.updateProfilePic);
module.exports=router;